function [fitresult, gof] = createFit(temp, cp)
%CREATEFIT(TEMP,CP)
%  Create a fit.
%
%  Data for 'cp_data_fitting' fit:
%      X Input : temp
%      Y Output: cp
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Aug-2020 22:14:56


%% Fit: 'cp_data_fitting'.
[xData, yData] = prepareCurveData( temp, cp );

% Set up fittype and options.
ft = fittype( 'poly3' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'cp_data_fitting' );
h = plot( fitresult, xData, yData );
legend( h, 'cp vs. temp', 'cp_data_fitting', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'temp', 'Interpreter', 'none' );
ylabel( 'cp', 'Interpreter', 'none' );
grid on


